-- +migrate Up
ALTER TABLE collections ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE requests ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE flows ADD COLUMN sort_order INTEGER NOT NULL DEFAULT 0;
