kind: pipeline
type: docker
name: airgap-build

# 폐쇄망 환경용 Drone CI 파이프라인
# - Nexus 프록시 레지스트리 사용
# - Portainer UI에서 스택 배포 (Drone에서 직접 배포하지 않음)

environment:
  # Nexus 레지스트리 (실제 환경에 맞게 수정)
  REGISTRY: nexus.example.com:8082
  # 프록시 설정 (mock data - 실제 환경에 맞게 수정)
  HTTP_PROXY: http://proxy.example.com:8080
  HTTPS_PROXY: http://proxy.example.com:8080
  NO_PROXY: localhost,127.0.0.1,.example.com,nexus.example.com

steps:
  - name: test-backend
    image: nexus.example.com:8082/golang:1.18-alpine
    environment:
      GOPROXY: http://nexus.example.com:8082/repository/go-proxy/,direct
      GONOSUMDB: "*"
    commands:
      - apk add --no-cache gcc musl-dev
      - go mod download
      - go test ./...

  - name: test-frontend
    image: nexus.example.com:8082/node:20-alpine
    commands:
      - npm config set registry http://nexus.example.com:8082/repository/npm-proxy/
      - cd web
      - corepack enable && corepack prepare pnpm@8.15.0 --activate
      - pnpm config set registry http://nexus.example.com:8082/repository/npm-proxy/
      - pnpm install --frozen-lockfile
      - pnpm run lint
      - pnpm run build

  - name: build-push
    image: nexus.example.com:8082/plugins/docker
    settings:
      registry: nexus.example.com:8082
      repo: nexus.example.com:8082/relay
      dockerfile: Dockerfile.airgap
      build_args:
        - REGISTRY=nexus.example.com:8082
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: nexus_username
      password:
        from_secret: nexus_password
      insecure: true
    when:
      branch:
        - main
      event:
        - push

  # Portainer webhook을 통한 스택 업데이트 트리거 (선택사항)
  - name: notify-portainer
    image: nexus.example.com:8082/curlimages/curl:latest
    environment:
      PORTAINER_URL:
        from_secret: portainer_url
      PORTAINER_WEBHOOK:
        from_secret: portainer_stack_webhook
    commands:
      - |
        if [ -n "$PORTAINER_WEBHOOK" ]; then
          curl -k -X POST "${PORTAINER_URL}/api/stacks/webhooks/${PORTAINER_WEBHOOK}"
          echo "Portainer webhook triggered"
        else
          echo "Portainer webhook not configured, skipping..."
        fi
    when:
      branch:
        - main
      event:
        - push
      status:
        - success

trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request

---
# Secrets 설정 가이드:
# drone secret add --repository <repo> --name nexus_username --data <username>
# drone secret add --repository <repo> --name nexus_password --data <password>
# drone secret add --repository <repo> --name portainer_url --data https://portainer.example.com
# drone secret add --repository <repo> --name portainer_stack_webhook --data <webhook-id>
