// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package repository

import (
	"context"
	"database/sql"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (name, parent_id, workspace_id, sort_order) VALUES (?, ?, ?, ?) RETURNING id, name, parent_id, created_at, updated_at, workspace_id, variables, sort_order
`

type CreateCollectionParams struct {
	Name        string        `json:"name"`
	ParentID    sql.NullInt64 `json:"parent_id"`
	WorkspaceID int64         `json:"workspace_id"`
	SortOrder   int64         `json:"sort_order"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection,
		arg.Name,
		arg.ParentID,
		arg.WorkspaceID,
		arg.SortOrder,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Variables,
		&i.SortOrder,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = ?
`

func (q *Queries) DeleteCollection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, name, parent_id, created_at, updated_at, workspace_id, variables, sort_order FROM collections WHERE id = ? LIMIT 1
`

func (q *Queries) GetCollection(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Variables,
		&i.SortOrder,
	)
	return i, err
}

const getCollectionVariables = `-- name: GetCollectionVariables :one
SELECT variables FROM collections WHERE id = ?
`

func (q *Queries) GetCollectionVariables(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getCollectionVariables, id)
	var variables sql.NullString
	err := row.Scan(&variables)
	return variables, err
}

const getMaxChildCollectionSortOrder = `-- name: GetMaxChildCollectionSortOrder :one
SELECT COALESCE(MAX(sort_order), 0) AS max_sort_order FROM collections WHERE parent_id = ?
`

func (q *Queries) GetMaxChildCollectionSortOrder(ctx context.Context, parentID sql.NullInt64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxChildCollectionSortOrder, parentID)
	var max_sort_order interface{}
	err := row.Scan(&max_sort_order)
	return max_sort_order, err
}

const getMaxRootCollectionSortOrder = `-- name: GetMaxRootCollectionSortOrder :one
SELECT COALESCE(MAX(sort_order), 0) AS max_sort_order FROM collections WHERE workspace_id = ? AND parent_id IS NULL
`

func (q *Queries) GetMaxRootCollectionSortOrder(ctx context.Context, workspaceID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxRootCollectionSortOrder, workspaceID)
	var max_sort_order interface{}
	err := row.Scan(&max_sort_order)
	return max_sort_order, err
}

const listChildCollections = `-- name: ListChildCollections :many
SELECT id, name, parent_id, created_at, updated_at, workspace_id, variables, sort_order FROM collections WHERE parent_id = ? ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListChildCollections(ctx context.Context, parentID sql.NullInt64) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listChildCollections, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.Variables,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT id, name, parent_id, created_at, updated_at, workspace_id, variables, sort_order FROM collections WHERE workspace_id = ? ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListCollections(ctx context.Context, workspaceID int64) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollections, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.Variables,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootCollections = `-- name: ListRootCollections :many
SELECT id, name, parent_id, created_at, updated_at, workspace_id, variables, sort_order FROM collections WHERE parent_id IS NULL AND workspace_id = ? ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListRootCollections(ctx context.Context, workspaceID int64) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listRootCollections, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.Variables,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections SET name = ?, parent_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, parent_id, created_at, updated_at, workspace_id, variables, sort_order
`

type UpdateCollectionParams struct {
	Name     string        `json:"name"`
	ParentID sql.NullInt64 `json:"parent_id"`
	ID       int64         `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, updateCollection, arg.Name, arg.ParentID, arg.ID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Variables,
		&i.SortOrder,
	)
	return i, err
}

const updateCollectionParentAndSortOrder = `-- name: UpdateCollectionParentAndSortOrder :exec
UPDATE collections SET parent_id = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateCollectionParentAndSortOrderParams struct {
	ParentID  sql.NullInt64 `json:"parent_id"`
	SortOrder int64         `json:"sort_order"`
	ID        int64         `json:"id"`
}

func (q *Queries) UpdateCollectionParentAndSortOrder(ctx context.Context, arg UpdateCollectionParentAndSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateCollectionParentAndSortOrder, arg.ParentID, arg.SortOrder, arg.ID)
	return err
}

const updateCollectionSortOrder = `-- name: UpdateCollectionSortOrder :exec
UPDATE collections SET sort_order = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateCollectionSortOrderParams struct {
	SortOrder int64 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateCollectionSortOrder(ctx context.Context, arg UpdateCollectionSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateCollectionSortOrder, arg.SortOrder, arg.ID)
	return err
}

const updateCollectionVariables = `-- name: UpdateCollectionVariables :one
UPDATE collections SET variables = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, parent_id, created_at, updated_at, workspace_id, variables, sort_order
`

type UpdateCollectionVariablesParams struct {
	Variables sql.NullString `json:"variables"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateCollectionVariables(ctx context.Context, arg UpdateCollectionVariablesParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, updateCollectionVariables, arg.Variables, arg.ID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Variables,
		&i.SortOrder,
	)
	return i, err
}
