// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: environments.sql

package repository

import (
	"context"
	"database/sql"
)

const activateEnvironment = `-- name: ActivateEnvironment :one
UPDATE environments SET is_active = TRUE, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, variables, is_active, created_at, updated_at, workspace_id
`

func (q *Queries) ActivateEnvironment(ctx context.Context, id int64) (Environment, error) {
	row := q.db.QueryRowContext(ctx, activateEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Variables,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (name, variables, workspace_id) VALUES (?, ?, ?) RETURNING id, name, variables, is_active, created_at, updated_at, workspace_id
`

type CreateEnvironmentParams struct {
	Name        string         `json:"name"`
	Variables   sql.NullString `json:"variables"`
	WorkspaceID int64          `json:"workspace_id"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment, arg.Name, arg.Variables, arg.WorkspaceID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Variables,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const deactivateAllEnvironments = `-- name: DeactivateAllEnvironments :exec
UPDATE environments SET is_active = FALSE WHERE workspace_id = ?
`

func (q *Queries) DeactivateAllEnvironments(ctx context.Context, workspaceID int64) error {
	_, err := q.db.ExecContext(ctx, deactivateAllEnvironments, workspaceID)
	return err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments WHERE id = ?
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnvironment, id)
	return err
}

const getActiveEnvironment = `-- name: GetActiveEnvironment :one
SELECT id, name, variables, is_active, created_at, updated_at, workspace_id FROM environments WHERE is_active = TRUE AND workspace_id = ? LIMIT 1
`

func (q *Queries) GetActiveEnvironment(ctx context.Context, workspaceID int64) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getActiveEnvironment, workspaceID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Variables,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, name, variables, is_active, created_at, updated_at, workspace_id FROM environments WHERE id = ? LIMIT 1
`

func (q *Queries) GetEnvironment(ctx context.Context, id int64) (Environment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Variables,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, name, variables, is_active, created_at, updated_at, workspace_id FROM environments WHERE workspace_id = ? ORDER BY name
`

func (q *Queries) ListEnvironments(ctx context.Context, workspaceID int64) ([]Environment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Variables,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments SET name = ?, variables = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, variables, is_active, created_at, updated_at, workspace_id
`

type UpdateEnvironmentParams struct {
	Name      string         `json:"name"`
	Variables sql.NullString `json:"variables"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, updateEnvironment, arg.Name, arg.Variables, arg.ID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Variables,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}
