// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package repository

import (
	"context"
)

const createUploadedFile = `-- name: CreateUploadedFile :one
INSERT INTO uploaded_files (workspace_id, original_name, stored_name, content_type, size)
VALUES (?, ?, ?, ?, ?) RETURNING id, workspace_id, original_name, stored_name, content_type, size, created_at
`

type CreateUploadedFileParams struct {
	WorkspaceID  int64  `json:"workspace_id"`
	OriginalName string `json:"original_name"`
	StoredName   string `json:"stored_name"`
	ContentType  string `json:"content_type"`
	Size         int64  `json:"size"`
}

func (q *Queries) CreateUploadedFile(ctx context.Context, arg CreateUploadedFileParams) (UploadedFile, error) {
	row := q.db.QueryRowContext(ctx, createUploadedFile,
		arg.WorkspaceID,
		arg.OriginalName,
		arg.StoredName,
		arg.ContentType,
		arg.Size,
	)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OriginalName,
		&i.StoredName,
		&i.ContentType,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUploadedFile = `-- name: DeleteUploadedFile :exec
DELETE FROM uploaded_files WHERE id = ?
`

func (q *Queries) DeleteUploadedFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUploadedFile, id)
	return err
}

const getUploadedFile = `-- name: GetUploadedFile :one
SELECT id, workspace_id, original_name, stored_name, content_type, size, created_at FROM uploaded_files WHERE id = ? LIMIT 1
`

func (q *Queries) GetUploadedFile(ctx context.Context, id int64) (UploadedFile, error) {
	row := q.db.QueryRowContext(ctx, getUploadedFile, id)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OriginalName,
		&i.StoredName,
		&i.ContentType,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const listAllUploadedFiles = `-- name: ListAllUploadedFiles :many
SELECT id, stored_name FROM uploaded_files
`

type ListAllUploadedFilesRow struct {
	ID         int64  `json:"id"`
	StoredName string `json:"stored_name"`
}

func (q *Queries) ListAllUploadedFiles(ctx context.Context) ([]ListAllUploadedFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllUploadedFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUploadedFilesRow{}
	for rows.Next() {
		var i ListAllUploadedFilesRow
		if err := rows.Scan(&i.ID, &i.StoredName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
