// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flows.sql

package repository

import (
	"context"
	"database/sql"
)

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows (name, description, workspace_id) VALUES (?, ?, ?) RETURNING id, name, description, created_at, updated_at, workspace_id
`

type CreateFlowParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	WorkspaceID int64          `json:"workspace_id"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, createFlow, arg.Name, arg.Description, arg.WorkspaceID)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const createFlowStep = `-- name: CreateFlowStep :one
INSERT INTO flow_steps (flow_id, request_id, step_order, delay_ms, extract_vars, condition,
                        name, method, url, headers, body, body_type, cookies, proxy_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, flow_id, request_id, step_order, delay_ms, extract_vars, condition, name, method, url, headers, body, body_type, cookies, proxy_id, created_at, updated_at, workspace_id
`

type CreateFlowStepParams struct {
	FlowID      int64          `json:"flow_id"`
	RequestID   sql.NullInt64  `json:"request_id"`
	StepOrder   int64          `json:"step_order"`
	DelayMs     sql.NullInt64  `json:"delay_ms"`
	ExtractVars sql.NullString `json:"extract_vars"`
	Condition   sql.NullString `json:"condition"`
	Name        string         `json:"name"`
	Method      string         `json:"method"`
	Url         string         `json:"url"`
	Headers     sql.NullString `json:"headers"`
	Body        sql.NullString `json:"body"`
	BodyType    sql.NullString `json:"body_type"`
	Cookies     sql.NullString `json:"cookies"`
	ProxyID     sql.NullInt64  `json:"proxy_id"`
}

func (q *Queries) CreateFlowStep(ctx context.Context, arg CreateFlowStepParams) (FlowStep, error) {
	row := q.db.QueryRowContext(ctx, createFlowStep,
		arg.FlowID,
		arg.RequestID,
		arg.StepOrder,
		arg.DelayMs,
		arg.ExtractVars,
		arg.Condition,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Body,
		arg.BodyType,
		arg.Cookies,
		arg.ProxyID,
	)
	var i FlowStep
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.RequestID,
		&i.StepOrder,
		&i.DelayMs,
		&i.ExtractVars,
		&i.Condition,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.BodyType,
		&i.Cookies,
		&i.ProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const deleteFlow = `-- name: DeleteFlow :exec
DELETE FROM flows WHERE id = ?
`

func (q *Queries) DeleteFlow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFlow, id)
	return err
}

const deleteFlowStep = `-- name: DeleteFlowStep :exec
DELETE FROM flow_steps WHERE id = ?
`

func (q *Queries) DeleteFlowStep(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFlowStep, id)
	return err
}

const deleteFlowStepsByFlow = `-- name: DeleteFlowStepsByFlow :exec
DELETE FROM flow_steps WHERE flow_id = ?
`

func (q *Queries) DeleteFlowStepsByFlow(ctx context.Context, flowID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFlowStepsByFlow, flowID)
	return err
}

const getFlow = `-- name: GetFlow :one
SELECT id, name, description, created_at, updated_at, workspace_id FROM flows WHERE id = ? LIMIT 1
`

func (q *Queries) GetFlow(ctx context.Context, id int64) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlow, id)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getFlowStep = `-- name: GetFlowStep :one
SELECT id, flow_id, request_id, step_order, delay_ms, extract_vars, condition, name, method, url, headers, body, body_type, cookies, proxy_id, created_at, updated_at, workspace_id FROM flow_steps WHERE id = ? LIMIT 1
`

func (q *Queries) GetFlowStep(ctx context.Context, id int64) (FlowStep, error) {
	row := q.db.QueryRowContext(ctx, getFlowStep, id)
	var i FlowStep
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.RequestID,
		&i.StepOrder,
		&i.DelayMs,
		&i.ExtractVars,
		&i.Condition,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.BodyType,
		&i.Cookies,
		&i.ProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listFlowSteps = `-- name: ListFlowSteps :many
SELECT id, flow_id, request_id, step_order, delay_ms, extract_vars, condition, name, method, url, headers, body, body_type, cookies, proxy_id, created_at, updated_at, workspace_id FROM flow_steps WHERE flow_id = ? ORDER BY step_order
`

func (q *Queries) ListFlowSteps(ctx context.Context, flowID int64) ([]FlowStep, error) {
	rows, err := q.db.QueryContext(ctx, listFlowSteps, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowStep{}
	for rows.Next() {
		var i FlowStep
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.RequestID,
			&i.StepOrder,
			&i.DelayMs,
			&i.ExtractVars,
			&i.Condition,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.BodyType,
			&i.Cookies,
			&i.ProxyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlows = `-- name: ListFlows :many
SELECT id, name, description, created_at, updated_at, workspace_id FROM flows WHERE workspace_id = ? ORDER BY name
`

func (q *Queries) ListFlows(ctx context.Context, workspaceID int64) ([]Flow, error) {
	rows, err := q.db.QueryContext(ctx, listFlows, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flow{}
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlow = `-- name: UpdateFlow :one
UPDATE flows SET name = ?, description = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, description, created_at, updated_at, workspace_id
`

type UpdateFlowParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, updateFlow, arg.Name, arg.Description, arg.ID)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const updateFlowStep = `-- name: UpdateFlowStep :one
UPDATE flow_steps SET
    request_id = ?,
    step_order = ?,
    delay_ms = ?,
    extract_vars = ?,
    condition = ?,
    name = ?,
    method = ?,
    url = ?,
    headers = ?,
    body = ?,
    body_type = ?,
    cookies = ?,
    proxy_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, flow_id, request_id, step_order, delay_ms, extract_vars, condition, name, method, url, headers, body, body_type, cookies, proxy_id, created_at, updated_at, workspace_id
`

type UpdateFlowStepParams struct {
	RequestID   sql.NullInt64  `json:"request_id"`
	StepOrder   int64          `json:"step_order"`
	DelayMs     sql.NullInt64  `json:"delay_ms"`
	ExtractVars sql.NullString `json:"extract_vars"`
	Condition   sql.NullString `json:"condition"`
	Name        string         `json:"name"`
	Method      string         `json:"method"`
	Url         string         `json:"url"`
	Headers     sql.NullString `json:"headers"`
	Body        sql.NullString `json:"body"`
	BodyType    sql.NullString `json:"body_type"`
	Cookies     sql.NullString `json:"cookies"`
	ProxyID     sql.NullInt64  `json:"proxy_id"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateFlowStep(ctx context.Context, arg UpdateFlowStepParams) (FlowStep, error) {
	row := q.db.QueryRowContext(ctx, updateFlowStep,
		arg.RequestID,
		arg.StepOrder,
		arg.DelayMs,
		arg.ExtractVars,
		arg.Condition,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Body,
		arg.BodyType,
		arg.Cookies,
		arg.ProxyID,
		arg.ID,
	)
	var i FlowStep
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.RequestID,
		&i.StepOrder,
		&i.DelayMs,
		&i.ExtractVars,
		&i.Condition,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.BodyType,
		&i.Cookies,
		&i.ProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}
