// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: history.sql

package repository

import (
	"context"
	"database/sql"
)

const createHistory = `-- name: CreateHistory :one
INSERT INTO request_history (
    request_id, flow_id, method, url, request_headers, request_body,
    status_code, response_headers, response_body, duration_ms, error, workspace_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, request_id, flow_id, method, url, request_headers, request_body, status_code, response_headers, response_body, duration_ms, error, created_at, workspace_id
`

type CreateHistoryParams struct {
	RequestID       sql.NullInt64  `json:"request_id"`
	FlowID          sql.NullInt64  `json:"flow_id"`
	Method          string         `json:"method"`
	Url             string         `json:"url"`
	RequestHeaders  sql.NullString `json:"request_headers"`
	RequestBody     sql.NullString `json:"request_body"`
	StatusCode      sql.NullInt64  `json:"status_code"`
	ResponseHeaders sql.NullString `json:"response_headers"`
	ResponseBody    sql.NullString `json:"response_body"`
	DurationMs      sql.NullInt64  `json:"duration_ms"`
	Error           sql.NullString `json:"error"`
	WorkspaceID     int64          `json:"workspace_id"`
}

func (q *Queries) CreateHistory(ctx context.Context, arg CreateHistoryParams) (RequestHistory, error) {
	row := q.db.QueryRowContext(ctx, createHistory,
		arg.RequestID,
		arg.FlowID,
		arg.Method,
		arg.Url,
		arg.RequestHeaders,
		arg.RequestBody,
		arg.StatusCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
		arg.DurationMs,
		arg.Error,
		arg.WorkspaceID,
	)
	var i RequestHistory
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.FlowID,
		&i.Method,
		&i.Url,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.StatusCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.DurationMs,
		&i.Error,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const deleteHistory = `-- name: DeleteHistory :exec
DELETE FROM request_history WHERE id = ?
`

func (q *Queries) DeleteHistory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHistory, id)
	return err
}

const deleteOldHistory = `-- name: DeleteOldHistory :exec
DELETE FROM request_history WHERE created_at < datetime('now', '-30 days')
`

func (q *Queries) DeleteOldHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldHistory)
	return err
}

const getHistory = `-- name: GetHistory :one
SELECT id, request_id, flow_id, method, url, request_headers, request_body, status_code, response_headers, response_body, duration_ms, error, created_at, workspace_id FROM request_history WHERE id = ? LIMIT 1
`

func (q *Queries) GetHistory(ctx context.Context, id int64) (RequestHistory, error) {
	row := q.db.QueryRowContext(ctx, getHistory, id)
	var i RequestHistory
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.FlowID,
		&i.Method,
		&i.Url,
		&i.RequestHeaders,
		&i.RequestBody,
		&i.StatusCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.DurationMs,
		&i.Error,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listHistory = `-- name: ListHistory :many
SELECT id, request_id, flow_id, method, url, request_headers, request_body, status_code, response_headers, response_body, duration_ms, error, created_at, workspace_id FROM request_history WHERE workspace_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListHistoryParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	Limit       int64 `json:"limit"`
}

func (q *Queries) ListHistory(ctx context.Context, arg ListHistoryParams) ([]RequestHistory, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestHistory{}
	for rows.Next() {
		var i RequestHistory
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.FlowID,
			&i.Method,
			&i.Url,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.StatusCode,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.DurationMs,
			&i.Error,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryByRequest = `-- name: ListHistoryByRequest :many
SELECT id, request_id, flow_id, method, url, request_headers, request_body, status_code, response_headers, response_body, duration_ms, error, created_at, workspace_id FROM request_history WHERE request_id = ? ORDER BY created_at DESC LIMIT ?
`

type ListHistoryByRequestParams struct {
	RequestID sql.NullInt64 `json:"request_id"`
	Limit     int64         `json:"limit"`
}

func (q *Queries) ListHistoryByRequest(ctx context.Context, arg ListHistoryByRequestParams) ([]RequestHistory, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryByRequest, arg.RequestID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestHistory{}
	for rows.Next() {
		var i RequestHistory
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.FlowID,
			&i.Method,
			&i.Url,
			&i.RequestHeaders,
			&i.RequestBody,
			&i.StatusCode,
			&i.ResponseHeaders,
			&i.ResponseBody,
			&i.DurationMs,
			&i.Error,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
