// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Collection struct {
	ID          int64         `json:"id"`
	Name        string        `json:"name"`
	ParentID    sql.NullInt64 `json:"parent_id"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
	WorkspaceID int64         `json:"workspace_id"`
}

type Environment struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Variables   sql.NullString `json:"variables"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	WorkspaceID int64          `json:"workspace_id"`
}

type Flow struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	WorkspaceID int64          `json:"workspace_id"`
}

type FlowStep struct {
	ID          int64          `json:"id"`
	FlowID      int64          `json:"flow_id"`
	RequestID   sql.NullInt64  `json:"request_id"`
	StepOrder   int64          `json:"step_order"`
	DelayMs     sql.NullInt64  `json:"delay_ms"`
	ExtractVars sql.NullString `json:"extract_vars"`
	Condition   sql.NullString `json:"condition"`
	Name        string         `json:"name"`
	Method      string         `json:"method"`
	Url         string         `json:"url"`
	Headers     sql.NullString `json:"headers"`
	Body        sql.NullString `json:"body"`
	BodyType    sql.NullString `json:"body_type"`
	Cookies     sql.NullString `json:"cookies"`
	ProxyID     sql.NullInt64  `json:"proxy_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	WorkspaceID int64          `json:"workspace_id"`
}

type Proxy struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Url         string       `json:"url"`
	IsActive    sql.NullBool `json:"is_active"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	WorkspaceID int64        `json:"workspace_id"`
}

type Request struct {
	ID           int64          `json:"id"`
	CollectionID sql.NullInt64  `json:"collection_id"`
	Name         string         `json:"name"`
	Method       string         `json:"method"`
	Url          string         `json:"url"`
	Headers      sql.NullString `json:"headers"`
	Body         sql.NullString `json:"body"`
	BodyType     sql.NullString `json:"body_type"`
	Cookies      sql.NullString `json:"cookies"`
	ProxyID      sql.NullInt64  `json:"proxy_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	WorkspaceID  int64          `json:"workspace_id"`
}

type RequestHistory struct {
	ID              int64          `json:"id"`
	RequestID       sql.NullInt64  `json:"request_id"`
	FlowID          sql.NullInt64  `json:"flow_id"`
	Method          string         `json:"method"`
	Url             string         `json:"url"`
	RequestHeaders  sql.NullString `json:"request_headers"`
	RequestBody     sql.NullString `json:"request_body"`
	StatusCode      sql.NullInt64  `json:"status_code"`
	ResponseHeaders sql.NullString `json:"response_headers"`
	ResponseBody    sql.NullString `json:"response_body"`
	DurationMs      sql.NullInt64  `json:"duration_ms"`
	Error           sql.NullString `json:"error"`
	BodySize        sql.NullInt64  `json:"body_size"`
	IsBinary        sql.NullInt64  `json:"is_binary"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	WorkspaceID     int64          `json:"workspace_id"`
}

type Workspace struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
