// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proxies.sql

package repository

import (
	"context"
)

const activateProxy = `-- name: ActivateProxy :one
UPDATE proxies SET is_active = TRUE, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, url, is_active, created_at, updated_at
`

func (q *Queries) ActivateProxy(ctx context.Context, id int64) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, activateProxy, id)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProxy = `-- name: CreateProxy :one
INSERT INTO proxies (name, url) VALUES (?, ?) RETURNING id, name, url, is_active, created_at, updated_at
`

type CreateProxyParams struct {
	Name string `json:"name"`
	Url  string `json:"url"`
}

func (q *Queries) CreateProxy(ctx context.Context, arg CreateProxyParams) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, createProxy, arg.Name, arg.Url)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAllProxies = `-- name: DeactivateAllProxies :exec
UPDATE proxies SET is_active = FALSE
`

func (q *Queries) DeactivateAllProxies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deactivateAllProxies)
	return err
}

const deleteProxy = `-- name: DeleteProxy :exec
DELETE FROM proxies WHERE id = ?
`

func (q *Queries) DeleteProxy(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProxy, id)
	return err
}

const getActiveProxy = `-- name: GetActiveProxy :one
SELECT id, name, url, is_active, created_at, updated_at FROM proxies WHERE is_active = TRUE LIMIT 1
`

func (q *Queries) GetActiveProxy(ctx context.Context) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, getActiveProxy)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProxy = `-- name: GetProxy :one
SELECT id, name, url, is_active, created_at, updated_at FROM proxies WHERE id = ? LIMIT 1
`

func (q *Queries) GetProxy(ctx context.Context, id int64) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, getProxy, id)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProxies = `-- name: ListProxies :many
SELECT id, name, url, is_active, created_at, updated_at FROM proxies ORDER BY name
`

func (q *Queries) ListProxies(ctx context.Context) ([]Proxy, error) {
	rows, err := q.db.QueryContext(ctx, listProxies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Proxy{}
	for rows.Next() {
		var i Proxy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProxy = `-- name: UpdateProxy :one
UPDATE proxies SET name = ?, url = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, url, is_active, created_at, updated_at
`

type UpdateProxyParams struct {
	Name string `json:"name"`
	Url  string `json:"url"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateProxy(ctx context.Context, arg UpdateProxyParams) (Proxy, error) {
	row := q.db.QueryRowContext(ctx, updateProxy, arg.Name, arg.Url, arg.ID)
	var i Proxy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
