// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package repository

import (
	"context"
	"database/sql"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (collection_id, name, method, url, headers, body, body_type, cookies, proxy_id, workspace_id, pre_script, post_script, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, collection_id, name, method, url, headers, body, body_type, cookies, proxy_id, created_at, updated_at, workspace_id, pre_script, post_script, sort_order
`

type CreateRequestParams struct {
	CollectionID sql.NullInt64  `json:"collection_id"`
	Name         string         `json:"name"`
	Method       string         `json:"method"`
	Url          string         `json:"url"`
	Headers      sql.NullString `json:"headers"`
	Body         sql.NullString `json:"body"`
	BodyType     sql.NullString `json:"body_type"`
	Cookies      sql.NullString `json:"cookies"`
	ProxyID      sql.NullInt64  `json:"proxy_id"`
	WorkspaceID  int64          `json:"workspace_id"`
	PreScript    sql.NullString `json:"pre_script"`
	PostScript   sql.NullString `json:"post_script"`
	SortOrder    int64          `json:"sort_order"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Body,
		arg.BodyType,
		arg.Cookies,
		arg.ProxyID,
		arg.WorkspaceID,
		arg.PreScript,
		arg.PostScript,
		arg.SortOrder,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.BodyType,
		&i.Cookies,
		&i.ProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.PreScript,
		&i.PostScript,
		&i.SortOrder,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = ?
`

func (q *Queries) DeleteRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRequest, id)
	return err
}

const getMaxRequestSortOrder = `-- name: GetMaxRequestSortOrder :one
SELECT COALESCE(MAX(sort_order), 0) AS max_sort_order FROM requests WHERE collection_id = ?
`

func (q *Queries) GetMaxRequestSortOrder(ctx context.Context, collectionID sql.NullInt64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxRequestSortOrder, collectionID)
	var max_sort_order interface{}
	err := row.Scan(&max_sort_order)
	return max_sort_order, err
}

const getRequest = `-- name: GetRequest :one
SELECT id, collection_id, name, method, url, headers, body, body_type, cookies, proxy_id, created_at, updated_at, workspace_id, pre_script, post_script, sort_order FROM requests WHERE id = ? LIMIT 1
`

func (q *Queries) GetRequest(ctx context.Context, id int64) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.BodyType,
		&i.Cookies,
		&i.ProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.PreScript,
		&i.PostScript,
		&i.SortOrder,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT id, collection_id, name, method, url, headers, body, body_type, cookies, proxy_id, created_at, updated_at, workspace_id, pre_script, post_script, sort_order FROM requests WHERE workspace_id = ? ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListRequests(ctx context.Context, workspaceID int64) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequests, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.BodyType,
			&i.Cookies,
			&i.ProxyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.PreScript,
			&i.PostScript,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByCollection = `-- name: ListRequestsByCollection :many
SELECT id, collection_id, name, method, url, headers, body, body_type, cookies, proxy_id, created_at, updated_at, workspace_id, pre_script, post_script, sort_order FROM requests WHERE collection_id = ? ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListRequestsByCollection(ctx context.Context, collectionID sql.NullInt64) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.BodyType,
			&i.Cookies,
			&i.ProxyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.PreScript,
			&i.PostScript,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE requests SET
    collection_id = ?,
    name = ?,
    method = ?,
    url = ?,
    headers = ?,
    body = ?,
    body_type = ?,
    cookies = ?,
    proxy_id = ?,
    pre_script = ?,
    post_script = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, collection_id, name, method, url, headers, body, body_type, cookies, proxy_id, created_at, updated_at, workspace_id, pre_script, post_script, sort_order
`

type UpdateRequestParams struct {
	CollectionID sql.NullInt64  `json:"collection_id"`
	Name         string         `json:"name"`
	Method       string         `json:"method"`
	Url          string         `json:"url"`
	Headers      sql.NullString `json:"headers"`
	Body         sql.NullString `json:"body"`
	BodyType     sql.NullString `json:"body_type"`
	Cookies      sql.NullString `json:"cookies"`
	ProxyID      sql.NullInt64  `json:"proxy_id"`
	PreScript    sql.NullString `json:"pre_script"`
	PostScript   sql.NullString `json:"post_script"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, updateRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Body,
		arg.BodyType,
		arg.Cookies,
		arg.ProxyID,
		arg.PreScript,
		arg.PostScript,
		arg.ID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.BodyType,
		&i.Cookies,
		&i.ProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.PreScript,
		&i.PostScript,
		&i.SortOrder,
	)
	return i, err
}

const updateRequestCollectionAndSortOrder = `-- name: UpdateRequestCollectionAndSortOrder :exec
UPDATE requests SET collection_id = ?, sort_order = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRequestCollectionAndSortOrderParams struct {
	CollectionID sql.NullInt64 `json:"collection_id"`
	SortOrder    int64         `json:"sort_order"`
	ID           int64         `json:"id"`
}

func (q *Queries) UpdateRequestCollectionAndSortOrder(ctx context.Context, arg UpdateRequestCollectionAndSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestCollectionAndSortOrder, arg.CollectionID, arg.SortOrder, arg.ID)
	return err
}

const updateRequestSortOrder = `-- name: UpdateRequestSortOrder :exec
UPDATE requests SET sort_order = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRequestSortOrderParams struct {
	SortOrder int64 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateRequestSortOrder(ctx context.Context, arg UpdateRequestSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateRequestSortOrder, arg.SortOrder, arg.ID)
	return err
}
