// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package repository

import (
	"context"
	"database/sql"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (collection_id, name, method, url, headers, body, body_type, proxy_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, collection_id, name, method, url, headers, body, body_type, proxy_id, created_at, updated_at
`

type CreateRequestParams struct {
	CollectionID sql.NullInt64  `json:"collection_id"`
	Name         string         `json:"name"`
	Method       string         `json:"method"`
	Url          string         `json:"url"`
	Headers      sql.NullString `json:"headers"`
	Body         sql.NullString `json:"body"`
	BodyType     sql.NullString `json:"body_type"`
	ProxyID      sql.NullInt64  `json:"proxy_id"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, createRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Body,
		arg.BodyType,
		arg.ProxyID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.BodyType,
		&i.ProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = ?
`

func (q *Queries) DeleteRequest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRequest, id)
	return err
}

const getRequest = `-- name: GetRequest :one
SELECT id, collection_id, name, method, url, headers, body, body_type, proxy_id, created_at, updated_at FROM requests WHERE id = ? LIMIT 1
`

func (q *Queries) GetRequest(ctx context.Context, id int64) (Request, error) {
	row := q.db.QueryRowContext(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.BodyType,
		&i.ProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
SELECT id, collection_id, name, method, url, headers, body, body_type, proxy_id, created_at, updated_at FROM requests ORDER BY name
`

func (q *Queries) ListRequests(ctx context.Context) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.BodyType,
			&i.ProxyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByCollection = `-- name: ListRequestsByCollection :many
SELECT id, collection_id, name, method, url, headers, body, body_type, proxy_id, created_at, updated_at FROM requests WHERE collection_id = ? ORDER BY name
`

func (q *Queries) ListRequestsByCollection(ctx context.Context, collectionID sql.NullInt64) ([]Request, error) {
	rows, err := q.db.QueryContext(ctx, listRequestsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.BodyType,
			&i.ProxyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE requests SET
    collection_id = ?,
    name = ?,
    method = ?,
    url = ?,
    headers = ?,
    body = ?,
    body_type = ?,
    proxy_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? RETURNING id, collection_id, name, method, url, headers, body, body_type, proxy_id, created_at, updated_at
`

type UpdateRequestParams struct {
	CollectionID sql.NullInt64  `json:"collection_id"`
	Name         string         `json:"name"`
	Method       string         `json:"method"`
	Url          string         `json:"url"`
	Headers      sql.NullString `json:"headers"`
	Body         sql.NullString `json:"body"`
	BodyType     sql.NullString `json:"body_type"`
	ProxyID      sql.NullInt64  `json:"proxy_id"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (Request, error) {
	row := q.db.QueryRowContext(ctx, updateRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Body,
		arg.BodyType,
		arg.ProxyID,
		arg.ID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.BodyType,
		&i.ProxyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
