// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package repository

import (
	"context"
	"database/sql"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name) VALUES (?) RETURNING id, name, created_at, updated_at, variables
`

func (q *Queries) CreateWorkspace(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Variables,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at, updated_at, variables FROM workspaces WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorkspace(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Variables,
	)
	return i, err
}

const getWorkspaceVariables = `-- name: GetWorkspaceVariables :one
SELECT variables FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspaceVariables(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceVariables, id)
	var variables sql.NullString
	err := row.Scan(&variables)
	return variables, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, created_at, updated_at, variables FROM workspaces ORDER BY name
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Variables,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, created_at, updated_at, variables
`

type UpdateWorkspaceParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspace, arg.Name, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Variables,
	)
	return i, err
}

const updateWorkspaceVariables = `-- name: UpdateWorkspaceVariables :one
UPDATE workspaces SET variables = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING id, name, created_at, updated_at, variables
`

type UpdateWorkspaceVariablesParams struct {
	Variables sql.NullString `json:"variables"`
	ID        int64          `json:"id"`
}

func (q *Queries) UpdateWorkspaceVariables(ctx context.Context, arg UpdateWorkspaceVariablesParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, updateWorkspaceVariables, arg.Variables, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Variables,
	)
	return i, err
}
